language: node_js

node_js:
  - node

install:
  - npm install

script:
  - npm run cover

after_success:
  - bash <(curl -s https://codecov.io/bash) || true
  - ./node_modules/.bin/coveralls                 < coverage/lcov.info || true
  - ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info || true
